### ISSUE TITLE
Index.java:43-46: Replace parser with reactive version to...

### ISSUE THREAD

**Issue by 0pdd** [artipie/helm-adapter#187] opened 2021-07-16 12:19 UTC
The puzzle `112-f1a0e802` from #112 has to be resolved: 

https://github.com/artipie/helm-adapter/blob/98b4c8959e8aa32719cb69b549ec4d82a0685933/src/main/java/com/artipie/helm/metadata/Index.java#L43-L46

The puzzle was created by @g4s8 on 13-May-21. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by genryxy** [comment] 2021-07-16 12:21
Closes as duplicate of #113

**Closed by genryxy** 2021-07-16 12:21 UTC
